version: '2'
services:
  minisab:
    build:
      context: python
      dockerfile: Dockerfile_minisab_prod
  nginx:
    depends_on:
      - "minisab"
    image: minisab_nginx:1.1
    build:
      context: nginx
      args:
        - DEFAULT_NGINX=nginx-prod.conf
        - STATIC_NGINX=static
      dockerfile: Dockerfile_nginx
  cron:
    build:
      context: cron
      dockerfile: Dockerfile_cron
    image: minisab_cron:1.2
    depends_on:
      - "nginx"
    networks:
      minisab_default:
