version: '2'
services:
  minisab:
    volumes:
      - data:/data
    depends_on:
      - "redis"
    environment:
      - MINISAB_AUTRE_DBFILE=/app/minisab.db
      - MINISABINV_AUTRE_CONFIG=redis_docker.py;sab_docker.py
      - MINISABINV_CONFIG_FILE=/data/config.json
    image: minisab:2.11
    networks:
      minisab_default:
  nginx:
    depends_on:
      - "minisab"
    ports:
      - "$MINISAB_PORT:80"
    networks:
      minisab_default:
  redis:
      image: redis:4.0.8
      networks:
        minisab_default:
volumes:
  data: {}
networks:
  minisab_default:
