version: '2'
services:
  minisab:
    build:
      context: python
      dockerfile: Dockerfile_minisab
    image: minisab:dev
    environment:
      - MINISABINV_AUTRE_CONFIG=redis_docker.py;sab_docker.py
    volumes:
      - ./python:/app
  nginx:
    image: nginx:1.12
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static:/usr/share/nginx/html/minisab/static/
  sabnzbd:
    image: "sabnzbd/sabnzbd"
    environment:
      - SABNZBD_UID=$SABNZBD_USER
      - SABNZBD_GID=$SABNZBD_GROUP
    ports:
      - "$SABNZBD_PORT"
    volumes:
      - "$SABNZBD_MEDIA:/media"
      - "$SABNZBD_DATADIR:/datadir"
    networks:
      minisab_default:
