FROM nginx:1.12
ARG DEFAULT_NGINX
ARG STATIC_NGINX


ADD $DEFAULT_NGINX /etc/nginx/conf.d/default.conf
ADD $STATIC_NGINX /usr/share/nginx/html/minisab/static
RUN chmod 0755 -R /usr/share/nginx/html/minisab/static
