MINISAB_DBFILE = '/data/minisab.sqlite'
MINISAB_LOGFILE = '/data/minisab.log'
MINISAB_HOST_REDIS = 'redis' 
MINISAB_PORT_REDIS = 6379
MINISAB_HOST_SAB = None 
MINISAB_PORT_SAB = 0
MINISAB_CLE_SAB = None
MINISAB_CONFIG_FILE = None
