MINISAB_DBFILE = './db.sqlite'
MINISAB_LOGFILE = None
MINISAB_HOST_REDIS = 'localhost' 
MINISAB_PORT_REDIS = 6379
MINISAB_HOST_SAB = None 
MINISAB_PORT_SAB = 0
MINISAB_CLE_SAB = None
MINISAB_CONFIG_FILE = None
