FROM python:3.5

RUN pip3 install flask redis peewee gunicorn requests

RUN export LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN mkdir /app

WORKDIR /app

VOLUME /app

CMD export FLASK_APP=dev.py && export FLASK_DEBUG=1 && export FLASK_RUN_PORT=3000 && export FLASK_RUN_HOST=0.0.0.0 && flask run